### ISSUE TITLE
建议隐藏滚动条显示，更加美观

### ISSUE THREAD

**Issue by jiangfangzheng** [zizdlp/zbook#45]
支持作者！看了看示例，功能很不错！对界面有一个小建议：隐藏掉滚动条，界面上显示超多的滚动条不利于阅读，希望优化~

链接： https://zizdlp.com/zh/workspace/admin/o/docs/%E5%BC%80%E5%A7%8B/%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8

显示太多滚动条了：

![image](https://github.com/user-attachments/assets/573752e7-4092-4b9f-99a6-1a1171f0d569)

**Comment by zizdlp** [comment]
你这是什么浏览器，我使用safari和chrome 都没有这个现象,可以按照issue提供下操作系统浏览器等信息
<img width="1150" alt="截屏2024-09-15 07 43 41" src="https://github.com/user-attachments/assets/458effae-c8dd-40b6-8037-9663bc56c7b8">

**Comment by jiangfangzheng** [comment]
Win10 19044.4894
Google Chrome 128.0.6613.138 x64

![image](https://github.com/user-attachments/assets/f7171de3-3755-4666-a19a-31e48b3a78b8)

![image](https://github.com/user-attachments/assets/af008049-8c2b-47d6-95a6-15791d05dad4)

**Comment by zizdlp** [comment]
已经修复，感谢建议
